module.exports = {
  lang: "zh",
  title: "zyz Blog",
  head: [
    [
      "link",
      {
        rel: "icon",
        href: "http://image.zhuyuanzheng1.top/image-20220609004524311.png",
        // href: "https://gitee.com/zyzcode/gitee-pic/raw/master/20210626141637.png",
      },
    ],
    [
      "script",
      {
        src: "https://kit.fontawesome.com/e6a339ae70.js",
        crossorigin: "anonymous",
      },
    ],
    // ["style",{ src: "/blog-vuepress/style/base.css"}]
  ],
  dest: "dist",
  public: "public",
  base: "/zyzBlog/",
  description: "用Vupress架Blog",
  themeConfig: {
    logo: "http://image.zhuyuanzheng1.top/image-20220609004524311.png",
    // logo: "https://gitee.com/zyzcode/gitee-pic/raw/master/20210626141637.png",
    navbar: [
      {
        text: "前端网站导航",
        children: [
          { text: "前端网站导航", link: "http://zhuyuanzheng1.top/zyzBlog/前端网站导航.html" },
          { text: "css常用技巧", link: "http://zhuyuanzheng1.top/zyzBlog/css常用技巧.html" },
          { text: "vuejs网站导航", link: "http://zhuyuanzheng1.top/zyzBlog/vuejs网站导航.html" },
        ],
      },
      {
        text: "读书笔记",
        link: "http://zhuyuanzheng1.top/zyzBlog/read/",
        // link: "https://zyzweb.github.io/zyzBlog/read/index.html",
      },
      {
        text: "做过的项目",
        children: [{ text: "网易音乐播放器", link: "http://zhuyuanzheng1.top/zyzBlog/music/index.html" }],
      },
      {
        text: "gitee链接",
        link: "https://gitee.com/zyzcode/",
      },

      // NavbarItem
      // {
      //   text: '',
      //   link: ''
      // }

      // NavbarGroup
      // {
      //   text: 'Group',
      //   children: ['/group/foo.md', '/group/bar.md'],
      // },
      //'/guide/1.md',
    ],

    sidebar: [
      {
        text: "Home",
        link: "/",
        children: [
          {
            text: "github链接",
            link: "https://github.com/zyzweb",
            children: [],
          },
        ],
      },
      {
        isGroup: true,
        text: "Guide",
        children: [
          { text: "Mac使用", link: "/doc/Mac使用.md" },
          { text: "常用css mixin", link: "/doc/常用css mixin.md" },
          { text: "util", link: "/doc/js Utils.md" },
          { text: "总结", link: "/doc/总结.md" },
          { text: "算法", link: "/doc/算法.md" },
          { text: "常见报错", link: "/doc/常见报错.md" },
          { text: "创建自定义事件", link: "/doc/创建自定义事件.md" },
          { text: "翻墙vpn", link: "/doc/翻墙vpn.md" },
          { text: "快捷键", link: "/doc/快捷键.md" },
          { text: "快速定位bug", link: "/doc/快速定位bug.md" },
          { text: "浏览器加载外部脚本(油猴等)", link: "/doc/浏览器加载外部脚本(油猴等).md" },
          { text: "搜索", link: "/doc/搜索.md" },
          { text: "性能优化", link: "/doc/性能优化.md" },
          { text: "需求和项目", link: "/doc/需求和项目.md" },
          { text: "git", link: "/doc/git.md" },
          { text: "github pages和github actions 使用", link: "/doc/github pages和github actions 使用.md" },
          { text: "github", link: "/doc/github.md" },
          { text: "koa", link: "/doc/koa.md" },
          { text: "node", link: "/doc/node.md" },
          { text: "whistle调试", link: "/doc/whistle调试.md" },
          { text: "Xcode下载", link: "/doc/Xcode下载.md" },
          { text: "安卓玩机", link: "/doc/安卓玩机.md" },
          { text: "1password", link: "/doc/1password.md" },
          { text: "阿里云ECS", link: "/doc/阿里云ECS.md" },
          { text: "安装java环境", link: "/doc/安装java环境.md" },
          { text: "安装rz sz", link: "/doc/安装rz sz.md" },
          { text: "部署", link: "/doc/部署.md" },
          { text: "测试", link: "/doc/测试.md" },
          { text: "常见正则", link: "/doc/常见正则.md" },
          { text: "常见scheme总结", link: "/doc/常见scheme总结.md" },
          { text: "常用npm", link: "/doc/常用npm.md" },
          { text: "搭建github文件加速", link: "/doc/搭建github文件加速.md" },
          { text: "待解决的问题", link: "/doc/待解决的问题.md" },
          { text: "二进制Blob", link: "/doc/二进制Blob.md" },
          { text: "构建日志", link: "/doc/构建日志.md" },
          { text: "薅羊毛", link: "/doc/薅羊毛.md" },
          { text: "技术胖收藏夹", link: "/doc/技术胖收藏夹.md" },
          { text: "加密算法", link: "/doc/加密算法.md" },
          { text: "跨域", link: "/doc/跨域.md" },
          { text: "路由器", link: "/doc/路由器.md" },
          { text: "免费看视频", link: "/doc/免费看视频.md" },
          { text: "面试", link: "/doc/面试.md" },
          { text: "内网穿透", link: "/doc/内网穿透.md" },
          { text: "逆向", link: "/doc/逆向.md" },
          { text: "屏幕", link: "/doc/屏幕.md" },
          { text: "前端代码规范", link: "/doc/前端代码规范.md" },
          { text: "前端书籍推荐", link: "/doc/前端书籍推荐.md" },
          { text: "青龙面板使用", link: "/doc/青龙面板使用.md" },
          { text: "软件和网站", link: "/doc/软件和网站.md" },
          { text: "设计模式", link: "/doc/设计模式.md" },
          { text: "手游私服", link: "/doc/手游私服.md" },
          { text: "搜狗输入法", link: "/doc/搜狗输入法.md" },
          { text: "淘宝联盟", link: "/doc/淘宝联盟.md" },
          { text: "腾讯云", link: "/doc/腾讯云.md" },
          { text: "图床", link: "/doc/图床.md" },
          { text: "外部二次分享", link: "/doc/外部二次分享.md" },
          { text: "网络", link: "/doc/网络.md" },
          { text: "微前端", link: "/doc/微前端.md" },
          { text: "微信群机器人", link: "/doc/微信群机器人.md" },
          { text: "下载", link: "/doc/下载.md" },
          { text: "安卓玩机", link: "/doc/安卓玩机.md" },
          { text: "小程序 微信公众号", link: "/doc/小程序 微信公众号.md" },
          { text: "硬件", link: "/doc/硬件.md" },
          { text: "油猴脚本", link: "/doc/油猴脚本.md" },
          { text: "云手机", link: "/doc/云手机.md" },
          { text: "字体", link: "/doc/字体.md" },
          { text: "arrify-源码解析", link: "/doc/arrify-源码解析.md" },
          { text: "babel", link: "/doc/babel.md" },
          { text: "Bark自定义推送", link: "/doc/Bark自定义推送.md" },
          { text: "chrome", link: "/doc/chrome.md" },
          { text: "chrome插件", link: "/doc/chrome插件.md" },
          { text: "crontab使用", link: "/doc/crontab使用.md" },
          { text: "docker基础", link: "/doc/docker基础.md" },
          { text: "emmet", link: "/doc/emmet.md" },
          { text: "es6新语法", link: "/doc/es6新语法.md" },
          { text: "http升级https", link: "/doc/http升级https.md" },
          { text: "Iphone8 ios14.3越狱", link: "/doc/Iphone8 ios14.3越狱.md" },
          { text: "Iterm2", link: "/doc/Iterm2.md" },
          { text: "jsdoc", link: "/doc/jsdoc.md" },
          { text: "kali使用", link: "/doc/kali使用.md" },
          { text: "lerna使用", link: "/doc/lerna使用.md" },
          { text: "LG手机", link: "/doc/LG手机.md" },
          { text: "linux", link: "/doc/linux.md" },
          { text: "nginx", link: "/doc/nginx.md" },
          { text: "notion使用指南", link: "/doc/notion使用指南.md" },
          { text: "npm", link: "/doc/npm.md" },
          { text: "oauth2.0 JWT", link: "/doc/oauth2.0 JWT.md" },
          { text: "open api", link: "/doc/open api.md" },
          { text: "pm2", link: "/doc/pm2.md" },
          { text: "pnpm", link: "/doc/pnpm.md" },
          { text: "postman", link: "/doc/postman.md" },
          { text: "ps", link: "/doc/ps.md" },
          { text: "Puppeteer", link: "/doc/Puppeteer.md" },
          { text: "python", link: "/doc/python.md" },
          { text: "sass", link: "/doc/sass.md" },
          { text: "typescript", link: "/doc/typescript.md" },
          { text: "ui", link: "/doc/ui.md" },
          { text: "v8垃圾回收机制", link: "/doc/v8垃圾回收机制.md" },
          { text: "vim", link: "/doc/vim.md" },
          { text: "vite", link: "/doc/vite.md" },
          { text: "vue", link: "/doc/vue.md" },
          { text: "web安全", link: "/doc/web安全.md" },
          { text: "webpack", link: "/doc/webpack.md" },
          { text: "websocket", link: "/doc/websocket.md" },
          { text: "webstorm", link: "/doc/webstorm.md" },
          { text: "wifi连接", link: "/doc/wifi连接.md" },
          { text: "windows", link: "/doc/windows.md" },
          { text: "wireshark", link: "/doc/wireshark.md" },
          { text: "yarn", link: "/doc/yarn.md" },
          { text: "zsh", link: "/doc/zsh.md" },
        ],
      },
    ],
  },
};
